from django.urls import path
from .views import (
    SignUpView,
    dashboard,
    post_api,
    user_dashboard,
    search_results,
    profile,
    UserProfileView,
    AvailableModulesView, 
    EnrollModuleView,
    enrol,
    ModuleDetailView, 
    EnrollModuleView,
    module_detail,
    enrolled_modules,
    enrolled_module_details,
    feedback,
    teacher_modules,
    teacher_module_details,
    remove_student,
    upload_material,
    add_module,
    module_feedback,
    user_notifications,
    enter_chat,
    chat_room
    )

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('dashboard/', dashboard, name='dashboard'),  
    path('dashboard/<str:username>/', user_dashboard, name='dashboard'),
    path('dashboard/api/posts/', post_api, name='post_api'),
    path('search-results/', search_results, name='search_results'),
    path('profile/', profile, name='profile'), 
    path('api/profile/', UserProfileView.as_view(), name='profile_api'),
    path('enrol/', enrol, name='enrol'),
    path('api/enrol/', AvailableModulesView.as_view(), name='api_enrol'),
    path('api/enrol/<int:module_id>/', EnrollModuleView.as_view(), name='api_enroll_module'),
    path('api/module/<str:moduletitle>/', ModuleDetailView.as_view(), name='api_module_detail'),
    path('api/module/<str:moduletitle>/enroll/', EnrollModuleView.as_view(), name='api_enroll_module'),
    path('enrol/<str:moduletitle>/', module_detail, name='module_detail'),
    path('enrolled_modules/', enrolled_modules, name='enrolled_modules'),
    path('enrolled_module_details/<str:moduletitle>/', enrolled_module_details, name='enrolled_module_details'),
    path('feedback/', feedback, name='feedback'),
    path('teacher_modules/', teacher_modules, name='teacher_modules'),
    path('teacher_module_details/<str:moduletitle>/', teacher_module_details, name='teacher_module_details'),
    path('module/<int:module_id>/remove_student/<int:user_id>/', remove_student, name='remove_student'),
    path('upload_material/<int:moduleid>/', upload_material, name='upload_material'),
    path('add_module/', add_module, name='add_module'),
    path('teacher_module_details/<str:moduletitle>/feedbacks/', module_feedback, name='module_feedback'),
    path('notifications/', user_notifications, name='user_notifications'),
    path('chat/', enter_chat, name='enter_chat'),
    path('chat/<str:room_name>/', chat_room, name='chat_room'),
]