# Generated by Django 5.0.2 on 2024-03-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='module_media/'),
        ),
    ]
