# Generated by Django 5.0.2 on 2024-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_module_image_module_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='file',
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='module/thumbnail/'),
        ),
    ]
